//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vulcanova.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Vulcanova.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ScanQrCodeButton {
            get {
                return ResourceManager.GetString("ScanQrCodeButton", resourceCulture);
            }
        }
        
        internal static string SignInManuallyButton {
            get {
                return ResourceManager.GetString("SignInManuallyButton", resourceCulture);
            }
        }
        
        internal static string VulcanovaSubheadingLabel {
            get {
                return ResourceManager.GetString("VulcanovaSubheadingLabel", resourceCulture);
            }
        }
        
        internal static string GitHubLinkLabel {
            get {
                return ResourceManager.GetString("GitHubLinkLabel", resourceCulture);
            }
        }
        
        internal static string AddAccountLabel {
            get {
                return ResourceManager.GetString("AddAccountLabel", resourceCulture);
            }
        }
        
        internal static string AddAccountSubheadingLabel {
            get {
                return ResourceManager.GetString("AddAccountSubheadingLabel", resourceCulture);
            }
        }
        
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        internal static string EnterPinCodeLabel {
            get {
                return ResourceManager.GetString("EnterPinCodeLabel", resourceCulture);
            }
        }
        
        internal static string EnterPinCodeSubheadingLabel {
            get {
                return ResourceManager.GetString("EnterPinCodeSubheadingLabel", resourceCulture);
            }
        }
        
        internal static string QrScannerViewTitle {
            get {
                return ResourceManager.GetString("QrScannerViewTitle", resourceCulture);
            }
        }
        
        internal static string LuckyNumberTabTitle {
            get {
                return ResourceManager.GetString("LuckyNumberTabTitle", resourceCulture);
            }
        }
        
        internal static string GradesTabTitle {
            get {
                return ResourceManager.GetString("GradesTabTitle", resourceCulture);
            }
        }
        
        internal static string GradeWeightLabel {
            get {
                return ResourceManager.GetString("GradeWeightLabel", resourceCulture);
            }
        }
        
        internal static string NoLuckyNumber {
            get {
                return ResourceManager.GetString("NoLuckyNumber", resourceCulture);
            }
        }
        
        internal static string GradeCreatedDateLabel {
            get {
                return ResourceManager.GetString("GradeCreatedDateLabel", resourceCulture);
            }
        }
        
        internal static string GradeModifiedDateLabel {
            get {
                return ResourceManager.GetString("GradeModifiedDateLabel", resourceCulture);
            }
        }
        
        internal static string GradeEmptyNameLabel {
            get {
                return ResourceManager.GetString("GradeEmptyNameLabel", resourceCulture);
            }
        }
        
        internal static string PartialGradesTabTitle {
            get {
                return ResourceManager.GetString("PartialGradesTabTitle", resourceCulture);
            }
        }
        
        internal static string FinalGradesTabTitle {
            get {
                return ResourceManager.GetString("FinalGradesTabTitle", resourceCulture);
            }
        }
        
        internal static string ErrorInvalidToken {
            get {
                return ResourceManager.GetString("ErrorInvalidToken", resourceCulture);
            }
        }
        
        internal static string PredictedGradeLabel {
            get {
                return ResourceManager.GetString("PredictedGradeLabel", resourceCulture);
            }
        }
        
        internal static string FinalGradeLabel {
            get {
                return ResourceManager.GetString("FinalGradeLabel", resourceCulture);
            }
        }
        
        internal static string NoElementsLabel {
            get {
                return ResourceManager.GetString("NoElementsLabel", resourceCulture);
            }
        }
        
        internal static string NoPredictedGradesLabel {
            get {
                return ResourceManager.GetString("NoPredictedGradesLabel", resourceCulture);
            }
        }
        
        internal static string NoLessonsLabel {
            get {
                return ResourceManager.GetString("NoLessonsLabel", resourceCulture);
            }
        }
        
        internal static string NoExamsLabel {
            get {
                return ResourceManager.GetString("NoExamsLabel", resourceCulture);
            }
        }
        
        internal static string TimetableTabTitle {
            get {
                return ResourceManager.GetString("TimetableTabTitle", resourceCulture);
            }
        }
        
        internal static string AttendanceTabTitle {
            get {
                return ResourceManager.GetString("AttendanceTabTitle", resourceCulture);
            }
        }
        
        internal static string LessonTimeValueLabel {
            get {
                return ResourceManager.GetString("LessonTimeValueLabel", resourceCulture);
            }
        }
        
        internal static string LessonTimeLabel {
            get {
                return ResourceManager.GetString("LessonTimeLabel", resourceCulture);
            }
        }
        
        internal static string LessonDateLabel {
            get {
                return ResourceManager.GetString("LessonDateLabel", resourceCulture);
            }
        }
        
        internal static string LessonSubjectLabel {
            get {
                return ResourceManager.GetString("LessonSubjectLabel", resourceCulture);
            }
        }
        
        internal static string LessonTeacherLabel {
            get {
                return ResourceManager.GetString("LessonTeacherLabel", resourceCulture);
            }
        }
        
        internal static string NoAttendanceLabel {
            get {
                return ResourceManager.GetString("NoAttendanceLabel", resourceCulture);
            }
        }
        
        internal static string ExamsTabTitle {
            get {
                return ResourceManager.GetString("ExamsTabTitle", resourceCulture);
            }
        }
        
        internal static string ExamsSubjectLabel {
            get {
                return ResourceManager.GetString("ExamsSubjectLabel", resourceCulture);
            }
        }
        
        internal static string ExamsCreatorLabel {
            get {
                return ResourceManager.GetString("ExamsCreatorLabel", resourceCulture);
            }
        }
        
        internal static string ExamsDeadlineLabel {
            get {
                return ResourceManager.GetString("ExamsDeadlineLabel", resourceCulture);
            }
        }
        
        internal static string ExamsTypeLabel {
            get {
                return ResourceManager.GetString("ExamsTypeLabel", resourceCulture);
            }
        }
        
        internal static string ExamsCommentLabel {
            get {
                return ResourceManager.GetString("ExamsCommentLabel", resourceCulture);
            }
        }
        
        internal static string ExamsCreatedOnLabel {
            get {
                return ResourceManager.GetString("ExamsCreatedOnLabel", resourceCulture);
            }
        }
        
        internal static string SettingsTabTitle {
            get {
                return ResourceManager.GetString("SettingsTabTitle", resourceCulture);
            }
        }
        
        internal static string SettingsViewGradesSection {
            get {
                return ResourceManager.GetString("SettingsViewGradesSection", resourceCulture);
            }
        }
        
        internal static string GradesSettingsValueOfPlus {
            get {
                return ResourceManager.GetString("GradesSettingsValueOfPlus", resourceCulture);
            }
        }
        
        internal static string GradesSettingsValueOfMinus {
            get {
                return ResourceManager.GetString("GradesSettingsValueOfMinus", resourceCulture);
            }
        }
        
        internal static string HomeworkTabTitle {
            get {
                return ResourceManager.GetString("HomeworkTabTitle", resourceCulture);
            }
        }
        
        internal static string SettingsCustomValueLabel {
            get {
                return ResourceManager.GetString("SettingsCustomValueLabel", resourceCulture);
            }
        }
        
        internal static string SettingsCustomOptionText {
            get {
                return ResourceManager.GetString("SettingsCustomOptionText", resourceCulture);
            }
        }
        
        internal static string NoHomeworkLabel {
            get {
                return ResourceManager.GetString("NoHomeworkLabel", resourceCulture);
            }
        }
        
        internal static string FinalGradesAverage {
            get {
                return ResourceManager.GetString("FinalGradesAverage", resourceCulture);
            }
        }
        
        internal static string ShowErrorDetails {
            get {
                return ResourceManager.GetString("ShowErrorDetails", resourceCulture);
            }
        }
        
        internal static string ErrorAlertTitle {
            get {
                return ResourceManager.GetString("ErrorAlertTitle", resourceCulture);
            }
        }
        
        internal static string ReportErrorButton {
            get {
                return ResourceManager.GetString("ReportErrorButton", resourceCulture);
            }
        }
        
        internal static string IgnoreErrorButton {
            get {
                return ResourceManager.GetString("IgnoreErrorButton", resourceCulture);
            }
        }
        
        internal static string SessionErrorPopupTitle {
            get {
                return ResourceManager.GetString("SessionErrorPopupTitle", resourceCulture);
            }
        }
        
        internal static string SessionErrorAlertMessage {
            get {
                return ResourceManager.GetString("SessionErrorAlertMessage", resourceCulture);
            }
        }
        
        internal static string SessionErrorAlertAction {
            get {
                return ResourceManager.GetString("SessionErrorAlertAction", resourceCulture);
            }
        }
        
        internal static string HomeworkCreatorLabel {
            get {
                return ResourceManager.GetString("HomeworkCreatorLabel", resourceCulture);
            }
        }
        
        internal static string HomeworkCreatedOnLabel {
            get {
                return ResourceManager.GetString("HomeworkCreatedOnLabel", resourceCulture);
            }
        }
        
        internal static string HomeworkDueLabel {
            get {
                return ResourceManager.GetString("HomeworkDueLabel", resourceCulture);
            }
        }
        
        internal static string HomeworkContentLabel {
            get {
                return ResourceManager.GetString("HomeworkContentLabel", resourceCulture);
            }
        }
        
        internal static string HomeworkRequiresAnswerLabel {
            get {
                return ResourceManager.GetString("HomeworkRequiresAnswerLabel", resourceCulture);
            }
        }
        
        internal static string CommonYes {
            get {
                return ResourceManager.GetString("CommonYes", resourceCulture);
            }
        }
        
        internal static string CommonNo {
            get {
                return ResourceManager.GetString("CommonNo", resourceCulture);
            }
        }
        
        internal static string GradesAverageLabel {
            get {
                return ResourceManager.GetString("GradesAverageLabel", resourceCulture);
            }
        }
        
        internal static string GradesCountLabel {
            get {
                return ResourceManager.GetString("GradesCountLabel", resourceCulture);
            }
        }
        
        internal static string AddNewAccountButton {
            get {
                return ResourceManager.GetString("AddNewAccountButton", resourceCulture);
            }
        }
        
        internal static string ParentAccountLabel {
            get {
                return ResourceManager.GetString("ParentAccountLabel", resourceCulture);
            }
        }
        
        internal static string JustificationViewTitle {
            get {
                return ResourceManager.GetString("JustificationViewTitle", resourceCulture);
            }
        }
        
        internal static string JustificationMessageLabel {
            get {
                return ResourceManager.GetString("JustificationMessageLabel", resourceCulture);
            }
        }
        
        internal static string JustificationMessagePlaceholder {
            get {
                return ResourceManager.GetString("JustificationMessagePlaceholder", resourceCulture);
            }
        }
        
        internal static string CommonSubmit {
            get {
                return ResourceManager.GetString("CommonSubmit", resourceCulture);
            }
        }
        
        internal static string LessonJustifyAbsenceButton {
            get {
                return ResourceManager.GetString("LessonJustifyAbsenceButton", resourceCulture);
            }
        }
        
        internal static string CommonCancel {
            get {
                return ResourceManager.GetString("CommonCancel", resourceCulture);
            }
        }
        
        internal static string MessagesInboxFolder {
            get {
                return ResourceManager.GetString("MessagesInboxFolder", resourceCulture);
            }
        }
        
        internal static string MessagesSentFolder {
            get {
                return ResourceManager.GetString("MessagesSentFolder", resourceCulture);
            }
        }
        
        internal static string MessagesDeletedFolder {
            get {
                return ResourceManager.GetString("MessagesDeletedFolder", resourceCulture);
            }
        }
        
        internal static string MessagesTabTitle {
            get {
                return ResourceManager.GetString("MessagesTabTitle", resourceCulture);
            }
        }
        
        internal static string MessageReadByLabel {
            get {
                return ResourceManager.GetString("MessageReadByLabel", resourceCulture);
            }
        }
        
        internal static string NotesTabTitle {
            get {
                return ResourceManager.GetString("NotesTabTitle", resourceCulture);
            }
        }
        
        internal static string NoNotesLabel {
            get {
                return ResourceManager.GetString("NoNotesLabel", resourceCulture);
            }
        }
        
        internal static string NotePositiveLabel {
            get {
                return ResourceManager.GetString("NotePositiveLabel", resourceCulture);
            }
        }
        
        internal static string NotePointsLabel {
            get {
                return ResourceManager.GetString("NotePointsLabel", resourceCulture);
            }
        }
        
        internal static string NoteCreatorLabel {
            get {
                return ResourceManager.GetString("NoteCreatorLabel", resourceCulture);
            }
        }
        
        internal static string NoteCreatedOnLabel {
            get {
                return ResourceManager.GetString("NoteCreatedOnLabel", resourceCulture);
            }
        }
        
        internal static string NoteCommentLabel {
            get {
                return ResourceManager.GetString("NoteCommentLabel", resourceCulture);
            }
        }
        
        internal static string NoteNegativeLabel {
            get {
                return ResourceManager.GetString("NoteNegativeLabel", resourceCulture);
            }
        }
    }
}
