//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vulcanova.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Vulcanova.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ScanQrCodeButton {
            get {
                return ResourceManager.GetString("ScanQrCodeButton", resourceCulture);
            }
        }
        
        internal static string SignInManuallyButton {
            get {
                return ResourceManager.GetString("SignInManuallyButton", resourceCulture);
            }
        }
        
        internal static string VulcanovaSubheadingLabel {
            get {
                return ResourceManager.GetString("VulcanovaSubheadingLabel", resourceCulture);
            }
        }
        
        internal static string GitHubLinkLabel {
            get {
                return ResourceManager.GetString("GitHubLinkLabel", resourceCulture);
            }
        }
        
        internal static string AddAccountLabel {
            get {
                return ResourceManager.GetString("AddAccountLabel", resourceCulture);
            }
        }
        
        internal static string AddAccountSubheadingLabel {
            get {
                return ResourceManager.GetString("AddAccountSubheadingLabel", resourceCulture);
            }
        }
        
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        internal static string EnterPinCodeLabel {
            get {
                return ResourceManager.GetString("EnterPinCodeLabel", resourceCulture);
            }
        }
        
        internal static string EnterPinCodeSubheadingLabel {
            get {
                return ResourceManager.GetString("EnterPinCodeSubheadingLabel", resourceCulture);
            }
        }
        
        internal static string QrScannerViewTitle {
            get {
                return ResourceManager.GetString("QrScannerViewTitle", resourceCulture);
            }
        }
    }
}
