//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vulcanova.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vulcanova.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        internal static string AddAccountLabel {
            get {
                return ResourceManager.GetString("AddAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter below values from &apos;Dodaj konto&apos; section from the web diary client.
        /// </summary>
        internal static string AddAccountSubheadingLabel {
            get {
                return ResourceManager.GetString("AddAccountSubheadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new account.
        /// </summary>
        internal static string AddNewAccountButton {
            get {
                return ResourceManager.GetString("AddNewAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string AttendanceTabTitle {
            get {
                return ResourceManager.GetString("AttendanceTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CommonCancel {
            get {
                return ResourceManager.GetString("CommonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string CommonNo {
            get {
                return ResourceManager.GetString("CommonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string CommonSubmit {
            get {
                return ResourceManager.GetString("CommonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string CommonYes {
            get {
                return ResourceManager.GetString("CommonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        internal static string ComposeMessageSubjectLabel {
            get {
                return ResourceManager.GetString("ComposeMessageSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message.
        /// </summary>
        internal static string ComposeMessageTitle {
            get {
                return ResourceManager.GetString("ComposeMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        internal static string ComposeMessageToLabel {
            get {
                return ResourceManager.GetString("ComposeMessageToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter PIN code.
        /// </summary>
        internal static string EnterPinCodeLabel {
            get {
                return ResourceManager.GetString("EnterPinCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To finish adding account, enter the PIN code.
        /// </summary>
        internal static string EnterPinCodeSubheadingLabel {
            get {
                return ResourceManager.GetString("EnterPinCodeSubheadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorAlertTitle {
            get {
                return ResourceManager.GetString("ErrorAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API url found for given token.
        /// </summary>
        internal static string ErrorInvalidToken {
            get {
                return ResourceManager.GetString("ErrorInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string ExamsCommentLabel {
            get {
                return ResourceManager.GetString("ExamsCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        internal static string ExamsCreatedOnLabel {
            get {
                return ResourceManager.GetString("ExamsCreatedOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string ExamsCreatorLabel {
            get {
                return ResourceManager.GetString("ExamsCreatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ExamsDeadlineLabel {
            get {
                return ResourceManager.GetString("ExamsDeadlineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string ExamsSubjectLabel {
            get {
                return ResourceManager.GetString("ExamsSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams.
        /// </summary>
        internal static string ExamsTabTitle {
            get {
                return ResourceManager.GetString("ExamsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ExamsTypeLabel {
            get {
                return ResourceManager.GetString("ExamsTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final grade.
        /// </summary>
        internal static string FinalGradeLabel {
            get {
                return ResourceManager.GetString("FinalGradeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final grades average.
        /// </summary>
        internal static string FinalGradesAverage {
            get {
                return ResourceManager.GetString("FinalGradesAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final grades.
        /// </summary>
        internal static string FinalGradesTabTitle {
            get {
                return ResourceManager.GetString("FinalGradesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulcanova on GitHub.
        /// </summary>
        internal static string GitHubLinkLabel {
            get {
                return ResourceManager.GetString("GitHubLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date: {0:d}.
        /// </summary>
        internal static string GradeCreatedDateLabel {
            get {
                return ResourceManager.GetString("GradeCreatedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to untitled.
        /// </summary>
        internal static string GradeEmptyNameLabel {
            get {
                return ResourceManager.GetString("GradeEmptyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (modified: {0:d}).
        /// </summary>
        internal static string GradeModifiedDateLabel {
            get {
                return ResourceManager.GetString("GradeModifiedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string GradesAverageLabel {
            get {
                return ResourceManager.GetString("GradesAverageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades count.
        /// </summary>
        internal static string GradesCountLabel {
            get {
                return ResourceManager.GetString("GradesCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of minus.
        /// </summary>
        internal static string GradesSettingsValueOfMinus {
            get {
                return ResourceManager.GetString("GradesSettingsValueOfMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of plus.
        /// </summary>
        internal static string GradesSettingsValueOfPlus {
            get {
                return ResourceManager.GetString("GradesSettingsValueOfPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades.
        /// </summary>
        internal static string GradesTabTitle {
            get {
                return ResourceManager.GetString("GradesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight: {0}.
        /// </summary>
        internal static string GradeWeightLabel {
            get {
                return ResourceManager.GetString("GradeWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string HomeworkContentLabel {
            get {
                return ResourceManager.GetString("HomeworkContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        internal static string HomeworkCreatedOnLabel {
            get {
                return ResourceManager.GetString("HomeworkCreatedOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string HomeworkCreatorLabel {
            get {
                return ResourceManager.GetString("HomeworkCreatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string HomeworkDueLabel {
            get {
                return ResourceManager.GetString("HomeworkDueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer required.
        /// </summary>
        internal static string HomeworkRequiresAnswerLabel {
            get {
                return ResourceManager.GetString("HomeworkRequiresAnswerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homework.
        /// </summary>
        internal static string HomeworkTabTitle {
            get {
                return ResourceManager.GetString("HomeworkTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string IgnoreErrorButton {
            get {
                return ResourceManager.GetString("IgnoreErrorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter justification message.
        /// </summary>
        internal static string JustificationMessageLabel {
            get {
                return ResourceManager.GetString("JustificationMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please justify….
        /// </summary>
        internal static string JustificationMessagePlaceholder {
            get {
                return ResourceManager.GetString("JustificationMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justification.
        /// </summary>
        internal static string JustificationViewTitle {
            get {
                return ResourceManager.GetString("JustificationViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LessonDateLabel {
            get {
                return ResourceManager.GetString("LessonDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        internal static string LessonJustifyAbsenceButton {
            get {
                return ResourceManager.GetString("LessonJustifyAbsenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string LessonSubjectLabel {
            get {
                return ResourceManager.GetString("LessonSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string LessonTeacherLabel {
            get {
                return ResourceManager.GetString("LessonTeacherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string LessonTimeLabel {
            get {
                return ResourceManager.GetString("LessonTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:HH:mm} – {1:HH:mm}, Lesson {2}.
        /// </summary>
        internal static string LessonTimeValueLabel {
            get {
                return ResourceManager.GetString("LessonTimeValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky number.
        /// </summary>
        internal static string LuckyNumberTabTitle {
            get {
                return ResourceManager.GetString("LuckyNumberTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen by {0}/{1}.
        /// </summary>
        internal static string MessageReadByLabel {
            get {
                return ResourceManager.GetString("MessageReadByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string MessagesDeletedFolder {
            get {
                return ResourceManager.GetString("MessagesDeletedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        internal static string MessagesInboxFolder {
            get {
                return ResourceManager.GetString("MessagesInboxFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string MessagesSentFolder {
            get {
                return ResourceManager.GetString("MessagesSentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string MessagesTabTitle {
            get {
                return ResourceManager.GetString("MessagesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Attendance.
        /// </summary>
        internal static string NoAttendanceLabel {
            get {
                return ResourceManager.GetString("NoAttendanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No elements.
        /// </summary>
        internal static string NoElementsLabel {
            get {
                return ResourceManager.GetString("NoElementsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exams for the selected week.
        /// </summary>
        internal static string NoExamsLabel {
            get {
                return ResourceManager.GetString("NoExamsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No homework for the selected week.
        /// </summary>
        internal static string NoHomeworkLabel {
            get {
                return ResourceManager.GetString("NoHomeworkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lessons for the selected day.
        /// </summary>
        internal static string NoLessonsLabel {
            get {
                return ResourceManager.GetString("NoLessonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lucky number for today.
        /// </summary>
        internal static string NoLuckyNumber {
            get {
                return ResourceManager.GetString("NoLuckyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notes.
        /// </summary>
        internal static string NoNotesLabel {
            get {
                return ResourceManager.GetString("NoNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No predicted grades have been added or the register does not provide such data.
        /// </summary>
        internal static string NoPredictedGradesLabel {
            get {
                return ResourceManager.GetString("NoPredictedGradesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string NoteCommentLabel {
            get {
                return ResourceManager.GetString("NoteCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string NoteCreatedOnLabel {
            get {
                return ResourceManager.GetString("NoteCreatedOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string NoteCreatorLabel {
            get {
                return ResourceManager.GetString("NoteCreatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        internal static string NoteNegativeLabel {
            get {
                return ResourceManager.GetString("NoteNegativeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points .
        /// </summary>
        internal static string NotePointsLabel {
            get {
                return ResourceManager.GetString("NotePointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        internal static string NotePositiveLabel {
            get {
                return ResourceManager.GetString("NotePositiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string NotesTabTitle {
            get {
                return ResourceManager.GetString("NotesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parent&apos;s account.
        /// </summary>
        internal static string ParentAccountLabel {
            get {
                return ResourceManager.GetString("ParentAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial grades average.
        /// </summary>
        internal static string PartialGradesAverage {
            get {
                return ResourceManager.GetString("PartialGradesAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial grades.
        /// </summary>
        internal static string PartialGradesTabTitle {
            get {
                return ResourceManager.GetString("PartialGradesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted grade.
        /// </summary>
        internal static string PredictedGradeLabel {
            get {
                return ResourceManager.GetString("PredictedGradeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Scanner.
        /// </summary>
        internal static string QrScannerViewTitle {
            get {
                return ResourceManager.GetString("QrScannerViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string ReportErrorButton {
            get {
                return ResourceManager.GetString("ReportErrorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR code.
        /// </summary>
        internal static string ScanQrCodeButton {
            get {
                return ResourceManager.GetString("ScanQrCodeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SessionErrorAlertAction {
            get {
                return ResourceManager.GetString("SessionErrorAlertAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in required.
        /// </summary>
        internal static string SessionErrorAlertMessage {
            get {
                return ResourceManager.GetString("SessionErrorAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session error.
        /// </summary>
        internal static string SessionErrorPopupTitle {
            get {
                return ResourceManager.GetString("SessionErrorPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string SettingsCustomOptionText {
            get {
                return ResourceManager.GetString("SettingsCustomOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom value.
        /// </summary>
        internal static string SettingsCustomValueLabel {
            get {
                return ResourceManager.GetString("SettingsCustomValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable read receipts.
        /// </summary>
        internal static string SettingsDisableReadReceipts {
            get {
                return ResourceManager.GetString("SettingsDisableReadReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string SettingsMessagesSection {
            get {
                return ResourceManager.GetString("SettingsMessagesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTabTitle {
            get {
                return ResourceManager.GetString("SettingsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades.
        /// </summary>
        internal static string SettingsViewGradesSection {
            get {
                return ResourceManager.GetString("SettingsViewGradesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string ShowErrorDetails {
            get {
                return ResourceManager.GetString("ShowErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data manually.
        /// </summary>
        internal static string SignInManuallyButton {
            get {
                return ResourceManager.GetString("SignInManuallyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable.
        /// </summary>
        internal static string TimetableTabTitle {
            get {
                return ResourceManager.GetString("TimetableTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unofficial Vulcan UONET+ mobile client.
        /// </summary>
        internal static string VulcanovaSubheadingLabel {
            get {
                return ResourceManager.GetString("VulcanovaSubheadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recipient has seen the message.
        /// </summary>
        internal static string WhoSeenMessageDialogNobodyContent {
            get {
                return ResourceManager.GetString("WhoSeenMessageDialogNobodyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen by.
        /// </summary>
        internal static string WhoSeenMessageDialogTitle {
            get {
                return ResourceManager.GetString("WhoSeenMessageDialogTitle", resourceCulture);
            }
        }
    }
}
